name: tiktok_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # For SVG image
  flutter_svg: ^1.1.6

  # shimmer effect
  fade_shimmer: ^2.0.1

  # Google fonts
  google_fonts:

  # For state management
  flutter_bloc: ^8.0.1

  # Case
  recase: ^4.1.0

  # For Toast messages
  fluttertoast: ^8.0.8

  # Compress video
  video_compress: ^3.1.2

  # Pick image from gallery
  image_picker: ^0.8.4+4

  lottie: ^2.2.0

  stacked_services: ^0.8.6
  stacked: ^2.1.7
  cached_network_image: ^3.0.0
  cached_video_player: ^2.0.3

  get_it: ^7.2.0
  video_player: ^2.2.11

  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
    - assets/svg/
    - assets/image/

  fonts:
    - family: Bold
      fonts:
        - asset: fonts/Gilroy-Bold.otf
    - family: Medium
      fonts:
        - asset: fonts/Gilroy-Medium.otf
    - family: Semibold
      fonts:
        - asset: fonts/Gilroy-Semibold.otf
    - family: Regular
      fonts:
        - asset: fonts/Gilroy-Regular.otf
    - family: TikTokIcons
      fonts:
        - asset: fonts/TikTokIcons.ttf






