// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL4OMd6BhbN3jGtcphxcH03W241N7MQTg',
    appId: '1:621586262976:android:00eeb03454e5cc7d3eb625',
    messagingSenderId: '621586262976',
    projectId: 'gleaming-baton-369011',
    storageBucket: 'gleaming-baton-369011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvFhQcjIG9-b-kzgF0OBxJbka-GfwXNyk',
    appId: '1:621586262976:ios:1a7caa22cff2d4323eb625',
    messagingSenderId: '621586262976',
    projectId: 'gleaming-baton-369011',
    storageBucket: 'gleaming-baton-369011.appspot.com',
    androidClientId: '621586262976-9fludf3rujvldcasp5frvcimaqglum0n.apps.googleusercontent.com',
    iosClientId: '621586262976-hcmrct57nj6mru3gkojgvgphqjatrsav.apps.googleusercontent.com',
    iosBundleId: 'com.example.crowdpad',
  );
}
